name       : haruna
version    : 0.12.1
release    : 11
source     :
    - https://cdn.download.kde.org/stable/haruna/haruna-0.12.1.tar.xz : 0435b336d9a19097920f1d92fe5df2e352a9431bd84ce6a34fe225930ea38ede
homepage   : https://invent.kde.org/multimedia/haruna/
license    :
    - BSD-3-Clause
    - CC-BY-4
    - CC-BY-SA-4
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Video player built with Qt/QML on top of libmpv.
description: |
    Video player built with Qt/QML on top of libmpv.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(mpv)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - breeze-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc
