name       : haruna
version    : 0.10.3
release    : 8
source     :
    - https://download.kde.org/stable/haruna/haruna-0.10.3.tar.xz : 4d21eaa709dd3b9f393e2252c4642127ab5da9781a74c903dafba64ae3f9d296
homepage   : https://invent.kde.org/multimedia/haruna/
license    :
    - BSD-3-Clause
    - CC-BY-4
    - CC-BY-SA-4
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Video player built with Qt/QML on top of libmpv.
description: |
    Video player built with Qt/QML on top of libmpv.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(mpv)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - breeze-devel
    - kdoctools-devel
    - kfilemetadata-devel
    - kiconthemes-devel
    - kio-devel
    - kirigami2-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc
